<?php

// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Local language pack from http://lms.dev.one
 *
 * @package    mod
 * @subpackage bigbluebuttonbn
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['activityoverview'] = 'You have upcoming Virtual Classroom sessions';
$string['bigbluebuttonbn'] = 'Virtual Classroom';
$string['bigbluebuttonbn:addinstance'] = 'Add a new Virtual Classroom activity';
$string['bigbluebuttonbn:join'] = 'Join a Virtual Classroom';
$string['bigbluebuttonbn:managerecordings'] = 'Manage Virtual Classroom recordings';
$string['config_extended_capabilities_description'] = 'Configuration for extended capabilities when the Virtual Classroom server offers them.';
$string['config_preuploadpresentation_description'] = 'These settings enable or disable options in the UI and also define default values for these options. The feature works only if the Moodle server is accessible to Virtual Classroom..';
$string['config_recording_default_description'] = 'If enabled the sessions created in Virtual Classroom will have recording capabilities.';
$string['config_server_url'] = 'Virtual Classroom Server URL';
$string['config_server_url_description'] = 'The URL of your BigBlueButton server must end with /bigbluebutton/. (This default URL is for a Virtual Classroom server provided by Blindside Networks that you can use for testing.)';
$string['config_shared_secret'] = 'Virtual Classroom Shared Secret';
$string['config_shared_secret_description'] = 'The security salt of your BigBlueButton server. (This default salt is for a Virtual Classroom server provided by Blindside Networks that you can use for testing.)';
$string['config_uidelegation_enabled_description'] = 'These settings enable or disable the UI delegation to the Virtual Classroom server.';
$string['config_waitformoderator_cache_ttl_description'] = 'To support a heavy load of clients this plugin makes use of a cache. This parameter defines the time the cache will be kept before the next request is sent to the Virtual Classroom server.';
$string['config_warning_bigbluebuttonbn_cfg_deprecated'] = 'Virtual Classroom is making use of config.php with a global variable that has been deprecated. Please convert the file as it will not be supported in future versions';
$string['event_activity_created'] = 'Virtual Classroom activity created';
$string['event_activity_deleted'] = 'Virtual Classroom activity deleted';
$string['event_activity_modified'] = 'Virtual Classroom activity deleted';
$string['event_activity_viewed'] = 'Virtual Classroom activity viewed';
$string['event_activity_viewed_all'] = 'Virtual Classroom activity management viewed';
$string['event_meeting_created'] = 'Virtual Classroom meeting created';
$string['event_meeting_ended'] = 'Virtual Classroom meeting forcibly ended';
$string['event_meeting_joined'] = 'Virtual Classroom meeting joined';
$string['event_meeting_left'] = 'Virtual Classroom meeting left';
$string['general_error_unable_connect'] = 'Unable to connect. Please check the url of the Virtual Classroom server AND check to see if the Virtual Classroom server is running.';
$string['index_error_unable_display'] = 'Unable to display the meetings. Please check the url of the Virtual Classroom server AND check to see if the Virtual Classroom server is running.';
$string['index_heading'] = 'Virtual Classroom Rooms';
$string['mod_form_field_instanceprofiles_help'] = 'Select the type for this Virtual Classroom instance.';
$string['mod_form_field_voicebridge_help'] = 'Voice conference number that participants enter to join the voice conference when using dial-in. A number between 1 and 9999 must be typed. If the value is 0 the static voicebridge number will be ignored and a random number will be generated by Virtual Classroom. A number 7 will preced to the four digits typed';
$string['mod_form_field_welcome_default'] = '<br>Welcome to <b>%%CONFNAME%%</b>!<br><br>For help on using Virtual Classroom see these (short) <a href="event:http://www.bigbluebutton.org/content/videos"><u>tutorial videos</u></a>.<br><br>To join the audio bridge click the phone icon (top center). <b>Please use a headset to avoid causing background noise for others.</b>';
$string['mod_form_field_welcome_help'] = 'Replaces the default message setted up for the Virtual Classroom server. The message can includes keywords (%%CONFNAME%%, %%DIALNUM%%, %%CONFNUM%%) which will be substituted automatically, and also html tags like <b>...</b> or <i></i>';
$string['modulename'] = 'Virtual Classroom';
$string['modulename_help'] = 'BigBlueButtonBN lets you create from within Moodle links to real-time on-line classrooms using BigBlueButton, an open source web conferencing system for distance education. Using Virtual Classroom you can specify for the title, description, calendar entry (which gives a date range for joining the session), groups, and details about the recording of the on-line session. To view later recordings, add a RecordingsBN resource to this course.';
$string['modulenameplural'] = 'Virtual Classroom';
$string['pluginadministration'] = 'Virtual Classroom administration';
$string['pluginname'] = 'Virtual Classroom';
$string['privacy:metadata:bigbluebutton'] = 'In order to create and join Virtual Classroom sessions, user data needs to be exchanged with the server.';
$string['privacy:metadata:bigbluebutton:fullname'] = 'The fullname of the user accessing the Virtual Classroom server.';
$string['privacy:metadata:bigbluebutton:userid'] = 'The userid of the user accessing the Virtual Classroom server.';
$string['privacy:metadata:bigbluebuttonbn'] = 'Stores the configuration for the room or activity that defines the features and general behaviour of the Virtual Classroom session.';
$string['view_error_bigbluebutton'] = 'Virtual Classroom responded with errors. {$a}';
$string['view_error_create'] = 'The Virtual Classroom server responded with an error message, the meeting could not be created.';
$string['view_error_current_state_not_found'] = 'Current state was not found. The recording may have been deleted or the Virtual Classroom server is not compatible with the action performed.';
$string['view_error_unable_join'] = 'Unable to join the meeting. Please check the url of the Virtual Classroom server AND check to see if the Virtual Classroom server is running.';
$string['view_error_unable_join_student'] = 'Unable to connect to the Virtual Classroom server. Please contact your Teacher or the Administrator.';
$string['view_error_unable_join_teacher'] = 'Unable to connect to the Virtual Classroom server. Please contact the Administrator.';
$string['view_message_recordings_disabled'] = 'Recordings were disabled on this server. Virtual Classroom instances for recordings only can not be used.';
$string['view_noguests'] = 'The Virtual Classroom is not open to guests';
$string['view_recording_publish_link_deleted'] = 'This link can not be re-published because the actual recording does not exist in the current Virtual Classroom server. The link should be removed.';
$string['view_recording_unprotect_link_deleted'] = 'This link can not be un-protected because the actual recording does not exist in the current Virtual Classroom server. The link should be removed.';
$string['view_warning_default_server'] = 'This Moodle server is making use of the Virtual Classroom testing server that comes pre-configured by default. It should be replaced for production.';
