def project = 'modern-cubist-206411'
def  appName = 'oa-app'
def  feSvcName = "${appName}-frontend"
def  imageTag = "gcr.io/${project}/${appName}:0.3.${env.BUILD_NUMBER}"


podTemplate(
    label: 'saas-stage-cd', 
    inheritFrom: 'default',
    containers: [
        containerTemplate(
            name: 'gcloud', 
            image: 'gcr.io/cloud-builders/gcloud',
            ttyEnabled: true,
            command: 'cat'
        ),
        containerTemplate(
            name: 'kubectl', 
            image: 'gcr.io/cloud-builders/kubectl',
            ttyEnabled: true,
            command: 'cat'
        ),
        containerTemplate(
            name: 'docker', 
            image: 'docker:18.02',
            ttyEnabled: true,
            command: 'cat'
        ),
        // containerTemplate(
        //     name: 'helm', 
        //     image: 'ibmcom/k8s-helm:v2.6.0',
        //     ttyEnabled: true,
        //     command: 'cat'
        // ),        
    ],
volumes: [
  hostPathVolume(mountPath: '/home/gradle/.gradle', hostPath: '/tmp/jenkins/.gradle'),
  hostPathVolume(mountPath: '/var/run/docker.sock', hostPath: '/var/run/docker.sock')
]
) {
    node('saas-stage-cd') {
        try {         
            def subject = "STARTED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'"
            //slackSend ('YELLOW': '#FFFF00', message: "${subject} (${env.BUILD_URL})")

            def commitId
            stage ('Extract') {
                checkout scm
                commitId = sh(script: 'git rev-parse --short HEAD', returnStdout: true).trim()
            }

            def repository
            stage ('Build-stage') {
            
                container ('docker') {
                    docker.withRegistry("https://gcr.io", 'gcr:cd-jenkins') {
                        def dockerfile = '.docker/sidecar/Dockerfile'
                        def customImage = docker.build("gcr.io/modern-cubist-206411/${appName}:0.3.1.${env.BUILD_NUMBER}", "-f ${dockerfile} .")
                        /* Push the container to the custom Registry */
                        customImage.push()
                    }                
                }

            }
            

            stage('Cluster Switch - GKE') {
                    
                container('gcloud') {
                sh "gcloud container clusters get-credentials saas-stage --zone europe-west2-c --project modern-cubist-206411"
                }
                
            }  

            stage ('Deploy') {
                container ('kubectl') {                                    
                    sh "kubectl set image deployment/app app=gcr.io/modern-cubist-206411/${appName},image.tag=0.3.1.${env.BUILD_NUMBER}"
                    
                }
                
                // container ('helm') {                
                //     sh "/helm init --client-only --skip-refresh"                
                //     sh "/helm upgrade --install --wait --set image.repository=gcr.io/modern-cubist-206411/${appName},image.tag=0.3.${env.BUILD_NUMBER} webserver .helm/dev"                             
                // }
                
            }

        } catch (e) {
            // If there was an exception thrown, the build failed
            currentBuild.result = "FAILED"
            throw e
        } finally {
            // Success or failure, always send notifications
         
            buildStatus = currentBuild.result
            buildStatus =  buildStatus ?: 'SUCCESSFUL'

            // Default values
            def colorName = 'RED'
            def colorCode = '#FF0000'
            def subject = "${buildStatus}: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'"
            def summary = "${subject} (${env.BUILD_URL})"

            // Override default values based on build status
            if (buildStatus == 'STARTED') {
                color = 'YELLOW'
                colorCode = '#FFFF00'
            } else if (buildStatus == 'SUCCESSFUL') {
                color = 'GREEN'
                colorCode = '#00FF00'
            } else {
                color = 'RED'
                colorCode = '#FF0000'
            }

            // Send notifications
            //slackSend (color: colorCode, message: summary)
        }

        

    }

    
}
