apiVersion: v1
kind: ConfigMap
metadata:
  name: php-config
data:
  php.ini: |-
    file_uploads = On
    memory_limit = 256M
    upload_max_filesize = 1024M
    post_max_size = 1024M
    max_execution_time = 1800
    max_input_vars = 5000
